Bump MSRV to Rust 1.46+
Bumping due to im depending on a new version of sized-chunks. The error we got on Rust 1.43 was:

```
 error[E0658]: `if` is not allowed in a `const fn`
Error:    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/sized-chunks-0.6.3/src/inline_array/mod.rs:108:5
    |
108 | /     if element_size == 0 {
109 | |         usize::MAX
110 | |     } else {
111 | |         (host_size - header_size) / element_size
112 | |     }
    | |_____^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information
```