build: Fix larlpop dependency
The branch we were pulling larlpop from has been rebased and the commit disappeared causing the build to fail:

	error: failed to get `lalrpop` as a dependency of package `fathom v0.1.0 (/home/jtojnar/Projects/fathom/fathom)`

	Caused by:
	  failed to load source for dependency `lalrpop`

	Caused by:
	  Unable to update https://github.com/kmeakin/lalrpop?branch=raw-identifiers#a945c2a6

	Caused by:
	  object not found - no match for id (a945c2a68032f833142bdf6874cf280270c0ec8a); class=Odb (9); code=NotFound (-3)

Fortunately, the branch has been merged and is available in 0.19.9 release.